baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'The Programming, Logics and Semantics group at the IT-University of Copenhagen'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 20

[[menus.main]]
name = 'People'
pageRef = '/people'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 40

[[menus.main]]
name = 'Talks'
pageRef = '/talks'
weight = 50

[[menus.main]]
name = 'For Students'
pageRef = '/students'
weight = 60

[[menus.main]]
name = 'Directions'
pageRef = '/directions'
weight = 70

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
